import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Dozeri(),
        ]),
      ),
    );
  }
}

class Dozeri extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1280,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              side: BorderSide(width: 1),
              borderRadius: BorderRadius.circular(30),
            ),
            shadows: [
              BoxShadow(
                color: Color(0x3F000000),
                blurRadius: 4,
                offset: Offset(0, 4),
                spreadRadius: 0,
              )
            ],
          ),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 1280,
                  height: 64.58,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 1280,
                          height: 64.58,
                          decoration: BoxDecoration(color: Color(0xFF121212)),
                        ),
                      ),
                      Positioned(
                        left: 534,
                        top: 12.17,
                        child: Container(
                          width: 211,
                          height: 39.67,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/211x40"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 90,
                child: Text(
                  'Podešavanje Dozera',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 48,
                    fontFamily: 'BreezeSans',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 58,
                top: 478,
                child: Container(
                  width: 388.73,
                  height: 153.05,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 79.91,
                        top: -0,
                        child: Text(
                          'Dozer #3',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 43.34,
                            fontFamily: 'BreezeSans',
                            fontWeight: FontWeight.w300,
                          ),
                        ),
                      ),
                      Positioned(
                        left: -0,
                        top: 81.27,
                        child: Container(
                          width: 388.73,
                          height: 71.79,
                          decoration: ShapeDecoration(
                            color: Color(0xFFD9D9D9),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(13.54),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 131.38,
                        top: 98.87,
                        child: Text(
                          'Lek br 3.',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 32.51,
                            fontFamily: 'BreezeSans',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 687,
                top: 479,
                child: Container(
                  width: 404.01,
                  height: 159.07,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 83.05,
                        top: 0,
                        child: Text(
                          'Dozer #4',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 45.05,
                            fontFamily: 'BreezeSans',
                            fontWeight: FontWeight.w300,
                          ),
                        ),
                      ),
                      Positioned(
                        left: -0,
                        top: 84.46,
                        child: Container(
                          width: 404.01,
                          height: 74.61,
                          decoration: ShapeDecoration(
                            color: Color(0xFFD9D9D9),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(14.08),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 83.05,
                        top: 102.76,
                        child: Text(
                          'Unesite tekst...',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black.withOpacity(0.5),
                            fontSize: 33.78,
                            fontFamily: 'BreezeSans',
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 687,
                top: 234,
                child: Container(
                  width: 403.83,
                  height: 159,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 83.02,
                        top: 0,
                        child: Text(
                          'Dozer #2',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 45.03,
                            fontFamily: 'BreezeSans',
                            fontWeight: FontWeight.w300,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 84.42,
                        child: Container(
                          width: 403.83,
                          height: 74.58,
                          decoration: ShapeDecoration(
                            color: Color(0xFFD9D9D9),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(14.07),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 136.49,
                        top: 102.72,
                        child: Text(
                          'Lek br 2.',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 33.77,
                            fontFamily: 'BreezeSans',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 58,
                top: 234,
                child: Container(
                  width: 401.29,
                  height: 158,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 82.50,
                        top: 0,
                        child: Text(
                          'Dozer #1',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 44.74,
                            fontFamily: 'BreezeSans',
                            fontWeight: FontWeight.w300,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 83.89,
                        child: Container(
                          width: 401.29,
                          height: 74.11,
                          decoration: ShapeDecoration(
                            color: Color(0xFFD9D9D9),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(13.98),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 135.63,
                        top: 102.07,
                        child: Text(
                          'Lek br 1.',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 33.56,
                            fontFamily: 'BreezeSans',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}