import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Podesitelekinteraktiv03(),
        ]),
      ),
    );
  }
}

class Podesitelekinteraktiv03 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1280,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              side: BorderSide(width: 1),
              borderRadius: BorderRadius.circular(30),
            ),
            shadows: [
              BoxShadow(
                color: Color(0x3F000000),
                blurRadius: 4,
                offset: Offset(0, 4),
                spreadRadius: 0,
              )
            ],
          ),
          child: Stack(
            children: [
              Positioned(
                left: -1039,
                top: -1472,
                child: Container(
                  width: 1280,
                  height: 64.58,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 1280,
                          height: 64.58,
                          decoration: BoxDecoration(color: Color(0xFF121212)),
                        ),
                      ),
                      Positioned(
                        left: 534,
                        top: 12.17,
                        child: Container(
                          width: 211,
                          height: 39.67,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/211x40"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 90,
                child: Stack(
                  children: [
                    Positioned(
                      left: 0,
                      top: 0,
                      child: Text(
                        'Podešavanja za lek: “Lek”',
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 48,
                          fontFamily: 'BreezeSans',
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                    ),
                    Positioned(
                      left: 0,
                      top: 58,
                      child: Text(
                        'Molimo Vas, unesite Dozu, datum i vreme uzimanja leka.',
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 16,
                          fontFamily: 'BreezeSans',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 121,
                top: 340,
                child: Container(
                  width: 164,
                  height: 60,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 164,
                          height: 60,
                          decoration: ShapeDecoration(
                            color: Color(0xFFD8D8D8),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 42,
                        top: 8,
                        child: Text(
                          'Doza',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFF272727),
                            fontSize: 36,
                            fontFamily: 'BreezeSans',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 300,
                top: 340,
                child: Container(
                  width: 290,
                  height: 60,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 290,
                          height: 60,
                          decoration: ShapeDecoration(
                            color: Color(0xFFD8D8D8),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 30,
                        top: 8,
                        child: Text(
                          'Vreme/Datum',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFF272727),
                            fontSize: 36,
                            fontFamily: 'BreezeSans',
                            fontWeight: FontWeight.w400,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 121,
                top: 259,
                child: Container(
                  width: 164,
                  height: 60,
                  padding: const EdgeInsets.symmetric(horizontal: 35, vertical: 8),
                  decoration: ShapeDecoration(
                    color: Color(0xFFD8D8D8),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        '40mg',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Color(0xFF272727),
                          fontSize: 36,
                          fontFamily: 'BreezeSans',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 300,
                top: 259,
                child: Container(
                  width: 339,
                  height: 60,
                  padding: const EdgeInsets.symmetric(horizontal: 11, vertical: 8),
                  decoration: ShapeDecoration(
                    color: Color(0xFFD8D8D8),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        '1:30PM   16.7.2027.',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Color(0xFF272727),
                          fontSize: 36,
                          fontFamily: 'BreezeSans',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 28,
                top: 427,
                child: Container(
                  width: 92,
                  height: 92,
                  child: FlutterLogo(),
                ),
              ),
              Positioned(
                left: 29,
                top: 243,
                child: Container(
                  width: 92,
                  height: 92,
                  child: FlutterLogo(),
                ),
              ),
              Positioned(
                left: 29,
                top: 324,
                child: Container(
                  width: 92,
                  height: 92,
                  child: FlutterLogo(),
                ),
              ),
              Positioned(
                left: 0,
                top: -1,
                child: Container(
                  width: 1280,
                  height: 64.58,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 1280,
                          height: 64.58,
                          decoration: BoxDecoration(color: Color(0xFF121212)),
                        ),
                      ),
                      Positioned(
                        left: 534,
                        top: 12.17,
                        child: Container(
                          width: 211,
                          height: 39.67,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/211x40"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}