import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Mainscreen(),
        ]),
      ),
    );
  }
}

class Mainscreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1280,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              side: BorderSide(width: 1),
              borderRadius: BorderRadius.circular(30),
            ),
            shadows: [
              BoxShadow(
                color: Color(0x3F000000),
                blurRadius: 4,
                offset: Offset(0, 4),
                spreadRadius: 0,
              )
            ],
          ),
          child: Stack(
            children: [
              Positioned(
                left: 41,
                top: 488,
                child: Container(
                  width: 507,
                  height: 265,
                  padding: const EdgeInsets.symmetric(horizontal: 199, vertical: 18),
                  decoration: ShapeDecoration(
                    color: Color(0xFF87E4DB),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(19),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 377,
                        height: 153,
                        decoration: BoxDecoration(
                          image: DecorationImage(
                            image: NetworkImage("https://placehold.co/377x153"),
                            fit: BoxFit.fill,
                          ),
                        ),
                      ),
                      Expanded(
                        child: SizedBox(
                          width: 138,
                          child: Expanded(
                            child: SizedBox(
                              width: 138,
                              child: Text(
                                'Dozeri',
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 48,
                                  fontFamily: 'BreezeSans',
                                  fontWeight: FontWeight.w400,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 43,
                top: 196,
                child: Container(
                  width: 507,
                  height: 265,
                  padding: const EdgeInsets.symmetric(vertical: 18),
                  decoration: ShapeDecoration(
                    color: Color(0xFF64CFE0),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(19),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 218,
                        height: 135,
                        decoration: BoxDecoration(
                          image: DecorationImage(
                            image: NetworkImage("https://placehold.co/218x135"),
                            fit: BoxFit.fill,
                          ),
                        ),
                      ),
                      SizedBox(
                        width: 334,
                        child: SizedBox(
                          width: 334,
                          child: Text(
                            'Terapija',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 48,
                              fontFamily: 'BreezeSans',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 670,
                top: 149,
                child: Container(
                  width: 532,
                  height: 604,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'Trenutno stanje:',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 32.95,
                          fontFamily: 'BreezeSans',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                      Container(
                        width: 532,
                        height: 557,
                        padding: const EdgeInsets.symmetric(horizontal: 21, vertical: 18),
                        decoration: ShapeDecoration(
                          color: Color(0xFFE5EEEF),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(28),
                          ),
                          shadows: [
                            BoxShadow(
                              color: Color(0x3F000000),
                              blurRadius: 4,
                              offset: Offset(0, 4),
                              spreadRadius: 0,
                            )
                          ],
                        ),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              width: 465.01,
                              height: 85,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 196.99,
                                    top: 0,
                                    child: Container(
                                      width: 268.02,
                                      height: 34,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 34.64,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: ShapeDecoration(
                                                  color: Colors.white,
                                                  shape: RoundedRectangleBorder(
                                                    borderRadius: BorderRadius.only(
                                                      topRight: Radius.circular(17),
                                                      bottomRight: Radius.circular(17),
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 73.60,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Colors.white),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 112.57,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Colors.white),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 151.54,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Colors.white),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 190.50,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Colors.white),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 229.47,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Color(0xFFBBBBBB)),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 233.39,
                                            top: -0,
                                            child: Container(
                                              width: 34.64,
                                              height: 34,
                                              decoration: ShapeDecoration(
                                                color: Color(0xFFBBBBBB),
                                                shape: RoundedRectangleBorder(
                                                  borderRadius: BorderRadius.only(
                                                    topRight: Radius.circular(17),
                                                    bottomRight: Radius.circular(17),
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 45.99,
                                    top: 51,
                                    child: Text(
                                      '5/7 “Paracetamol” lekova preostalo',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 28,
                                        fontFamily: 'BreezeSans',
                                        fontWeight: FontWeight.w250,
                                        letterSpacing: -0.28,
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0,
                                    top: 0.50,
                                    child: Text(
                                      'Dozer #1:           ',
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 32.95,
                                        fontFamily: 'BreezeSans',
                                        fontWeight: FontWeight.w600,
                                        letterSpacing: -0.33,
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            const SizedBox(height: 26),
                            const SizedBox(height: 26),
                            Container(
                              width: 464.90,
                              height: 91.14,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 40.23,
                                    top: 57.14,
                                    child: Text(
                                      '3/7 “0695058090” lekova preostalo',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 28,
                                        fontFamily: 'BreezeSans',
                                        fontWeight: FontWeight.w250,
                                        letterSpacing: -0.28,
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0,
                                    top: 0,
                                    child: Text(
                                      'Dozer #2:           ',
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 32.95,
                                        fontFamily: 'BreezeSans',
                                        fontWeight: FontWeight.w600,
                                        letterSpacing: -0.33,
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 196.88,
                                    top: 2.80,
                                    child: Container(
                                      width: 268.02,
                                      height: 34,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 34.64,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: ShapeDecoration(
                                                  color: Color(0xFF87E4DB),
                                                  shape: RoundedRectangleBorder(
                                                    borderRadius: BorderRadius.only(
                                                      topRight: Radius.circular(17),
                                                      bottomRight: Radius.circular(17),
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 73.60,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Color(0xFF87E4DB)),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 112.57,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Color(0xFF87E4DB)),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 151.54,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Color(0xFFBBBBBB)),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 190.50,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Color(0xFFBBBBBB)),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 229.47,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Color(0xFFBBBBBB)),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 233.39,
                                            top: -0,
                                            child: Container(
                                              width: 34.64,
                                              height: 34,
                                              decoration: ShapeDecoration(
                                                color: Color(0xFFBBBBBB),
                                                shape: RoundedRectangleBorder(
                                                  borderRadius: BorderRadius.only(
                                                    topRight: Radius.circular(17),
                                                    bottomRight: Radius.circular(17),
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            const SizedBox(height: 26),
                            const SizedBox(height: 26),
                            Container(
                              width: 462.28,
                              height: 87.78,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 65.49,
                                    top: 53.78,
                                    child: Text(
                                      '4/7 “Fentanyl” lekova preostalo',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 28,
                                        fontFamily: 'BreezeSans',
                                        fontWeight: FontWeight.w250,
                                        letterSpacing: -0.28,
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0,
                                    top: 0,
                                    child: Text(
                                      'Dozer #3:           ',
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 32.95,
                                        fontFamily: 'BreezeSans',
                                        fontWeight: FontWeight.w600,
                                        letterSpacing: -0.33,
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 194.25,
                                    top: 2.66,
                                    child: Container(
                                      width: 268.02,
                                      height: 34,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 34.64,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: ShapeDecoration(
                                                  color: Color(0xFF00ACB1),
                                                  shape: RoundedRectangleBorder(
                                                    borderRadius: BorderRadius.only(
                                                      topRight: Radius.circular(17),
                                                      bottomRight: Radius.circular(17),
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 73.60,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Color(0xFF00ACB1)),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 112.57,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Color(0xFF00ACB1)),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 151.54,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Color(0xFF00ACB1)),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 190.50,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Color(0xFFBBBBBB)),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 229.47,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Color(0xFFBBBBBB)),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 233.39,
                                            top: -0,
                                            child: Container(
                                              width: 34.64,
                                              height: 34,
                                              decoration: ShapeDecoration(
                                                color: Color(0xFFBBBBBB),
                                                shape: RoundedRectangleBorder(
                                                  borderRadius: BorderRadius.only(
                                                    topRight: Radius.circular(17),
                                                    bottomRight: Radius.circular(17),
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            const SizedBox(height: 26),
                            const SizedBox(height: 26),
                            Container(
                              width: 462.34,
                              height: 90.69,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 88.37,
                                    top: 56.69,
                                    child: Text(
                                      '2/7 “Dspi” lekova preostalo',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 28,
                                        fontFamily: 'BreezeSans',
                                        fontWeight: FontWeight.w250,
                                        letterSpacing: -0.28,
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0,
                                    top: 0,
                                    child: Text(
                                      'Dozer #4:           ',
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 32.95,
                                        fontFamily: 'BreezeSans',
                                        fontWeight: FontWeight.w600,
                                        letterSpacing: -0.33,
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 194.31,
                                    top: 5.88,
                                    child: Container(
                                      width: 268.02,
                                      height: 34,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 34.64,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: ShapeDecoration(
                                                  color: Color(0xFF005963),
                                                  shape: RoundedRectangleBorder(
                                                    borderRadius: BorderRadius.only(
                                                      topRight: Radius.circular(17),
                                                      bottomRight: Radius.circular(17),
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 73.60,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Color(0xFF005963)),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 112.57,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Color(0xFFBBBBBB)),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 151.54,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Color(0xFFBBBBBB)),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 190.50,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Color(0xFFBBBBBB)),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 229.47,
                                            top: -0,
                                            child: Transform(
                                              transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                              child: Container(
                                                width: 34.64,
                                                height: 34,
                                                decoration: BoxDecoration(color: Color(0xFFBBBBBB)),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 233.39,
                                            top: -0,
                                            child: Container(
                                              width: 34.64,
                                              height: 34,
                                              decoration: ShapeDecoration(
                                                color: Color(0xFFBBBBBB),
                                                shape: RoundedRectangleBorder(
                                                  borderRadius: BorderRadius.only(
                                                    topRight: Radius.circular(17),
                                                    bottomRight: Radius.circular(17),
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 90,
                child: Stack(
                  children: [
                    Positioned(
                      left: 0,
                      top: 0,
                      child: Text(
                        'Zdravo, Dušanka!',
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 48,
                          fontFamily: 'BreezeSans',
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                    ),
                    Positioned(
                      left: 0,
                      top: 58,
                      child: Text(
                        'Izaberite željenu opciju.',
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 16,
                          fontFamily: 'BreezeSans',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 1280,
                  height: 64.58,
                  padding: const EdgeInsets.symmetric(horizontal: 75, vertical: 12),
                  decoration: BoxDecoration(color: Color(0xFF121212)),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 211,
                        height: 40,
                        decoration: BoxDecoration(
                          image: DecorationImage(
                            image: NetworkImage("https://placehold.co/211x40"),
                            fit: BoxFit.fill,
                          ),
                        ),
                      ),
                      Container(
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.end,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              width: 70,
                              height: 31,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 0,
                                    top: 0,
                                    child: Container(
                                      width: 70,
                                      height: 31,
                                      decoration: BoxDecoration(
                                        image: DecorationImage(
                                          image: NetworkImage("https://placehold.co/70x31"),
                                          fit: BoxFit.fill,
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 5,
                                    top: 5,
                                    child: SizedBox(
                                      width: 52.57,
                                      height: 20.91,
                                      child: SizedBox(
                                        width: 52.57,
                                        height: 20.91,
                                        child: Text(
                                          '94%',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: Color(0xFF121212),
                                            fontSize: 19.92,
                                            fontFamily: 'BreezeSans',
                                            fontWeight: FontWeight.w400,
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            const SizedBox(width: 18),
                            Container(
                              width: 37,
                              height: 34,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://placehold.co/37x34"),
                                  fit: BoxFit.fill,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}